[project]
name = "libbench"
version = "0.0.1"
description = "Just Run Stuff"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
libdraw = ["c/*"]
